Script started on 2016年03月11日 (週五) 22時47分25秒
]0;F74046153@2015cpp: ~/lab1F74046153@2015cpp:~/lab1$ sc[K[Kwhoami;;[Kpwd
F74046153
/home/F74046153/lab1
]0;F74046153@2015cpp: ~/lab1F74046153@2015cpp:~/lab1$ git config -l
user.name=ginedoc
user.email=bear110088@gmail.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
alias.st=status
]0;F74046153@2015cpp: ~/lab1F74046153@2015cpp:~/lab1$ git clone https://github.com/ ginedoc/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
]0;F74046153@2015cpp: ~/lab1F74046153@2015cpp:~/lab1$ exit

Script done on 2016年03月11日 (週五) 22時48分22秒
